extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - prettier
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended

env:
  browser: true
  es2021: true

parserOptions:
  sourceType: module
  ecmaVersion: 12 # default for env.es2021, but needed for vue-eslint-parser

ignorePatterns:
  - .github
  - dist

rules:
  curly: error
  eqeqeq: error
  object-shorthand: error
  prefer-const: error
